/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LayoutServiceDesksRouteImport } from './routes/_layout/service-desks'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutAppSlugRouteImport } from './routes/_layout/app.$slug'
import { Route as LayoutCatalogAppsIndexRouteImport } from './routes/_layout/catalog.apps.index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutServiceDesksRoute = LayoutServiceDesksRouteImport.update({
  id: '/service-desks',
  path: '/service-desks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppSlugRoute = LayoutAppSlugRouteImport.update({
  id: '/app/$slug',
  path: '/app/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogAppsIndexRoute = LayoutCatalogAppsIndexRouteImport.update({
  id: '/catalog/apps/',
  path: '/catalog/apps/',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LayoutLoginRoute
  '/service-desks': typeof LayoutServiceDesksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/$slug': typeof LayoutAppSlugRoute
  '/catalog/apps/': typeof LayoutCatalogAppsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LayoutLoginRoute
  '/service-desks': typeof LayoutServiceDesksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof LayoutIndexRoute
  '/app/$slug': typeof LayoutAppSlugRoute
  '/catalog/apps': typeof LayoutCatalogAppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/service-desks': typeof LayoutServiceDesksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/app/$slug': typeof LayoutAppSlugRoute
  '/_layout/catalog/apps/': typeof LayoutCatalogAppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/service-desks'
    | '/auth/callback'
    | '/app/$slug'
    | '/catalog/apps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/service-desks'
    | '/auth/callback'
    | '/'
    | '/app/$slug'
    | '/catalog/apps'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/login'
    | '/_layout/service-desks'
    | '/auth/callback'
    | '/_layout/'
    | '/_layout/app/$slug'
    | '/_layout/catalog/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/service-desks': {
      id: '/_layout/service-desks'
      path: '/service-desks'
      fullPath: '/service-desks'
      preLoaderRoute: typeof LayoutServiceDesksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/$slug': {
      id: '/_layout/app/$slug'
      path: '/app/$slug'
      fullPath: '/app/$slug'
      preLoaderRoute: typeof LayoutAppSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog/apps/': {
      id: '/_layout/catalog/apps/'
      path: '/catalog/apps'
      fullPath: '/catalog/apps/'
      preLoaderRoute: typeof LayoutCatalogAppsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutServiceDesksRoute: typeof LayoutServiceDesksRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAppSlugRoute: typeof LayoutAppSlugRoute
  LayoutCatalogAppsIndexRoute: typeof LayoutCatalogAppsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutServiceDesksRoute: LayoutServiceDesksRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAppSlugRoute: LayoutAppSlugRoute,
  LayoutCatalogAppsIndexRoute: LayoutCatalogAppsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
