services:
  postgres-app-catalog-example:
    container_name: postgres-app-catalog-example
    image: postgres:16
    environment:
      POSTGRES_USER: app-catalog
      POSTGRES_PASSWORD: app-catalog
      POSTGRES_DB: app-catalog-core
    ports:
      - "5533:5432"
